# Datos generales del proyecto (Opcional pero recomendado)
app.name=COLABORADOR

# ===================================
# CONFIGURACIÓN DE POSTGRESQL
# ===================================

spring.datasource.url=jdbc:postgresql://172.16.166.8:5432/aden?currentSchema=sipacweb_desarrollo
spring.datasource.username=erick
spring.datasource.password=3r1ck

#Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================

# Dialecto para que Hibernate sepa hablar con PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Estrategia de creación de tablas (opciones: update, validate, create, none)
spring.jpa.hibernate.ddl-auto=none

# Muestra las consultas SQL ejecutadas en la consola de Eclipse (muy útil para depurar)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true